[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@chainlink=lib/chainlink/contracts']

optimizer = true
optimizer_runs = 2_000
fs_permissions = [{ access = "read", path = "./"}]